= rpg-template-adoc

A template for writing content similar to RPG source books using https://asciidoctor.org/[asciidoctor].

== Usage

Install https://www.ruby-lang.org/en/documentation/installation/[Ruby] and https://bundler.io/[Bundler].

This project's dependencies can be installed in a project-local directory with `bundle install`.
Then, different targets can be built (in `./build`) using the command `bundle exec rake <TARGET>`,
where `<TARGET>` can be `html`, `epub`, `pdf`, or empty for all of them.
The target `clean` will remove all built files.

See the https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writer's Guide], or for more details on the syntax, the https://asciidoctor.org/docs/user-manual/[User Manual].

One of asciidoctor's strengths is building a large document from component parts.
This template has separate top-level directories for asciidoctor documents which will be included as sections, images, tables.
You can even import entire asciidoctor projects from other contributors (for example, if you share a common ruleset)!

:leveloffset: +2

include::sections/README.adoc[]

include::images/README.adoc[]

include::tables/README.adoc[]

include::imports/README.adoc[]

:leveloffset: -2

Always include a `LICENSE.adoc` with your work if you would like it to be accessible to others.
